name: dagster_dbt_project
version: '1.0'
profile: dagster_dbt
model-paths: ["models"]

seeds:
  dagster_dbt_project:
    examples:
      historic_transactions_example:
        enabled: false
      seed_account_mapping_simplefin_example:
        enabled: false
      seed_account_mapping_historic_example:
        enabled: false
      seed_transaction_exclusions_example:
        enabled: false