dagster_dbt:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('DBT_POSTGRES_USER', 'dagster') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'dagster') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_POSTGRES_DBNAME', 'dagster') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'analytics') }}"
      threads: 2
  target: dev