version: 2

sources:
  - name: predictions_sources
    database: "{{ target.database }}"
    schema: analytics
    tables:
      - name: predicted_transactions
        description: "Predicted transactions from the transaction classifier."
        columns:
          - name: transaction_id
          - name: predicted_master_category
          - name: prediction_confidence
          - name: model_version
          - name: prediction_timestamp
  - name: public_sources
    database: "{{ target.database }}"
    schema: public
    tables:
      - name: simplefin
        description: "SimpleFIN raw financial data. Loaded every xxx days."
        columns:
          - name: transaction_id
          - name: account_id
          - name: account_name
          - name: institution_domain
          - name: institution_name
          - name: amount
          - name: posted
          - name: posted_date
          - name: transacted_at
          - name: transacted_date
          - name: description
          - name: pending
      - name: user_categories
        description: "User-defined category overrides for transactions. Created and edited from the UI."
        columns:
          - name: transaction_id
          - name: master_category
          - name: source_category
          - name: notes
          - name: validated
          - name: updated_by
          - name: updated_at
